# Generated by Django 2.1.1 on 2018-09-19 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=3)),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[345678]\\d{9}', message='请输入正确的手机格式')])),
                ('password', models.CharField(max_length=11)),
                ('money', models.FloatField(null=True)),
            ],
        ),
    ]
